---- CMP KEYWORDS
--" gray
--highlight! CmpItemAbbrDeprecated guibg=NONE gui=strikethrough guifg=#808080
--" blue
--highlight! CmpItemAbbrMatch guibg=NONE guifg=#569CD6
--highlight! CmpItemAbbrMatchFuzzy guibg=NONE guifg=#569CD6
--" light blue
--highlight! CmpItemKindVariable guibg=NONE guifg=#9CDCFE
--highlight! CmpItemKindInterface guibg=NONE guifg=#9CDCFE
--highlight! CmpItemKindText guibg=NONE guifg=#9CDCFE
--" pink
--highlight! CmpItemKindFunction guibg=NONE guifg=#C586C0
--highlight! CmpItemKindMethod guibg=NONE guifg=#C586C0
--" front
--highlight! CmpItemKindKeyword guibg=NONE guifg=#D4D4D4
--highlight! CmpItemKindProperty guibg=NONE guifg=#D4D4D4
--highlight! CmpItemKindUnit guibg=NONE guifg=#D4D4D4
---- LspSaga KEYWORDS
--LspSagaFinderSelection
--LspFloatWinNormal
--LspFloatWinBorder
--LspSagaBorderTitle
--TargetWord
--ReferencesCount
--DefinitionCount
--TargetFileName
--DefinitionIcon
--ReferencesIcon
--ProviderTruncateLine
--SagaShadow
--LspSagaFinderSelection
--DiagnosticTruncateLine
--DiagnosticError
--DiagnosticWarning
--DiagnosticInformation
--DiagnosticHint
--DefinitionPreviewTitle
--LspSagaShTruncateLine
--LspSagaDocTruncateLine
--LineDiagTuncateLine
--LspSagaCodeActionTitle
--LspSagaCodeActionTruncateLine
--LspSagaCodeActionContent
--LspSagaRenamePromptPrefix
--LspSagaRenameBorder
--LspSagaHoverBorder
--LspSagaSignatureHelpBorder
--LspSagaCodeActionBorder
--LspSagaAutoPreview
--LspSagaDefPreviewBorder
--LspLinesDiagBorder
--
--
--OctoDirty 	ErrorMsg
--OctoIssueTitle 	PreProc
--OctoIssueId 	Question
--OctoEmpty 	Comment
--OctoFloat 	NormalNC
--OctoDate 	Comment
--OctoSymbol 	Comment
--OctoTimelineItemHeading 	Comment
--OctoDetailsLabel 	Title
--OctoMissingDetails 	Comment
--OctoDetailsValue 	Identifier
--OctoDiffHunkPosition 	NormalFloat
--OctoCommentLine 	TabLineSel
--OctoEditable 	NormalFloat bg
--OctoViewer 	GitHub color
--OctoBubble 	NormalFloat
--OctoBubbleGreen 	GitHub color
--OctoBubbleRed 	GitHub color
--OctoUser 	OctoBubble
--OctoUserViewer 	OctoViewer
--OctoReaction 	OctoBubble
--OctoReactionViewer 	OctoViewer
--OctoPassingTest 	GitHub color
--OctoFailingTest 	GitHub color
--OctoPullAdditions 	GitHub color
--OctoPullDeletions 	GitHub color
--OctoPullModifications 	GitHub color
--OctoStateOpen 	GitHub color
--OctoStateClosed 	GitHub color
--OctoStateMerge 	GitHub color
--OctoStatePending 	GitHub color
--OctoStateApproved 	OctoStateOpen
--OctoStateChangesRequested 	OctoStateClosed
--OctoStateCommented 	Normal
--OctoStateDismissed 	OctoStateClosed
